version: "3.3"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER:${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS:${RABBITMQ_PASS}
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq:/var/lib/rabbitmq/

volumes:
  rabbitmq: